// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOG8WCtga7LmeisEuxTuiMksK4uOM74Fg',
    appId: '1:266742758932:web:ee26974354375dcbf8b101',
    messagingSenderId: '266742758932',
    projectId: 'daily-receipt-app',
    authDomain: 'daily-receipt-app.firebaseapp.com',
    storageBucket: 'daily-receipt-app.firebasestorage.app',
    measurementId: 'G-4C42PCME1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5tibS_Hqw-TE2G1YmPzgqs7MoUaj1zw4',
    appId: '1:266742758932:android:2ce084fa8b72d801f8b101',
    messagingSenderId: '266742758932',
    projectId: 'daily-receipt-app',
    storageBucket: 'daily-receipt-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA25LwrkLLIdykwn6yPBz6HrnW6RfkZ_tc',
    appId: '1:266742758932:ios:0add1fa7bd0fa480f8b101',
    messagingSenderId: '266742758932',
    projectId: 'daily-receipt-app',
    storageBucket: 'daily-receipt-app.firebasestorage.app',
    iosBundleId: 'com.easyandbeauty.dailyReceiptApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA25LwrkLLIdykwn6yPBz6HrnW6RfkZ_tc',
    appId: '1:266742758932:ios:00f973ac768ed3e1f8b101',
    messagingSenderId: '266742758932',
    projectId: 'daily-receipt-app',
    storageBucket: 'daily-receipt-app.firebasestorage.app',
    iosBundleId: 'com.easyandbeauty.dailyReceipt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOG8WCtga7LmeisEuxTuiMksK4uOM74Fg',
    appId: '1:266742758932:web:e2ea0eeb4876ffaff8b101',
    messagingSenderId: '266742758932',
    projectId: 'daily-receipt-app',
    authDomain: 'daily-receipt-app.firebaseapp.com',
    storageBucket: 'daily-receipt-app.firebasestorage.app',
    measurementId: 'G-CKJP5CQVG1',
  );
}
